<script src="{{ asset('js/reports.js') }}"></script>

<div class="container">
    <div class="wrapper-table">
    <table id="complaintTable" style="width:100%;height:90%" class="table table-striped">
        <thead>
            <tr>
                <th>amicably_settled</th>
                <th>assisted_by</th>
                <th>attendance_comp_one</th>
                <th>attendance_comp_two</th>
                <th>attendance_comp_three</th>
                <th>attendance_resp_one</th>
                <th>attendance_resp_three</th>
                <th>attendance_resp_two</th> 
                <th>brgy_captain_id</th>
                <th>case_complainant</th>
                <th>case_complainant_address</th>
                <th>case_date</th>
                <th>case_date_filed</th>
                <th>case_description</th>
                <th>case_dispo_one</th>
                <th>case_dispo_three</th>
                <th>case_dispo_two</th>
                <th>case_nature</th>
                <th>case_no</th>
                <th>case_referred_to_first</th>
                <th>case_referred_to_second</th>
                <th>case_respondent</th>
                <th>case_respondent_address</th>
                <th>case_status</th>
                <th>case_time</th>
                <th>certificate_to_file_action</th>
                <th>created_at</th>
                <th>day_of</th>
                <th>deleted_at</th>
                <th>duty_officer</th>
                <th>first_action_remarks</th>
                <th>id</th>
                <th>lack_of_interest</th>
                <th>lack_of_ment</th>
                <th>second_action_remarks</th>
                <th>sworn_date</th>
                <th>third_action_remarks</th>
                <th>updated_at</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>
    </div>

</div>